version: "3"
services:
  app:
    # build: ./app
    image: namanjain22/intern_task:app
    command: sh -c "sleep 10s; python3 app.py"
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: mysql-db
    image: namanjain22/intern_task:mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: Naman
        MYSQL_DATABASE: intern_task
        MYSQL_HOST: db
    ports:
        - '3306:3306'